import Head from 'next/head'
import Header from '../components/Header.js'
import Hero2 from '../components/Hero2.js'
import Section from '../components/Section.js'
import Location from '../components/Location.js'
import About from '../components/About.js'
import React from "react";

export default function AboutPage() {
    return (
        <div>
            <Head>
                <title>Mediteran</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Header />
            <Hero2 title="O nama" body="We always want to hear from you! Let us know how we can best help you and we'll do our very best." />
            <Section />
            <Location />
            <About />
        </div>
        )
    }
