import Head from 'next/head'
import Header from './components/Header.js'
import Hero2 from './components/Hero2.js'
import Section from './components/Section.js'
import Location from './components/Location.js'
import About from './components/About.js'

export default function AboutPage() {
    return (
        <div>
            <Head>
                <title>Mediteran</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://fonts.googleapis.com/css2?family=Poppins" rel="stylesheet" />
            </Head>
            <Header />
            <Hero2 />
            <Section />
            <Location />
            <About />
        </div>
        )
    }
