import Head from 'next/head'
import Header from './components/Header.js'
import Hero2 from './components/Hero2.js'
import Info from './components/Info.js'
import Contact from './components/Contact.js'

export default function ContactPage() {
    return (
        <div>
            <Head>
                <title>Mediteran</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Header />
            <Hero2 />
            <Info />
            <hr class="mb-32" />
            <Contact />
        </div>
        )
    }
