import Head from 'next/head'
import Header from '../components/Header.js'
import Hero2 from '../components/Hero2.js'
import Info from '../components/Info.js'
import Contact from '../components/Contact.js'
import React from "react";

export default function ContactPage() {
    return (
        <div>
            <Head>
                <title>Mediteran</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Header />
            <Hero2 title="Kontaktirajte nas" body="We always want to hear from you! Let us know how we can best help you and we'll do our very best." />
            <Info />
            <hr className="mb-32" />
            <Contact />
        </div>
        )
    }
