import React, { useEffect, useState } from 'react';
import { connect } from 'react-redux';
import { fetchArticles, fetchPages } from '../redux/actions';

import Head from 'next/head'
import Header from '../components/Header'
import ArticleList from '../components/ArticleList'
import Hero2 from '../components/Hero2'

function News({ articles, fetchArticles, pages, fetchPages }) {
    const [ page, setPage ] = useState(1);
    const [ leftDisabled, setLeftDisabled ] = useState(false);
    const [ rightDisabled, setRightDisabled ] = useState(false);

    useEffect(() => {
        fetchArticles(page);
        fetchPages();

        if (page === 1) {
            setLeftDisabled(true)
        } else {
            setLeftDisabled(false)
        }

        if (page === pages) {
            setRightDisabled(true)
        } else {
            setRightDisabled(false)
        }
    }, [page]);

    return (
        <div>
            <Head>
                <title>Mediteran</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <div>
                <Header />
                <Hero2 />
                <ArticleList articles={articles} />
                <div>
                    <button className="mr-3" disabled={leftDisabled} onClick={() => setPage(page - 1)}>
                        Left
                    </button>
                    <button disabled={rightDisabled} onClick={() => setPage(page + 1)}>
                        Right
                    </button>
                </div>
            </div>
        </div>
    )
}

const mapStateToProps = state => {
    return {
        articles: state.articles,
        pages: state.pages
    };
};

export default connect(
    mapStateToProps,
    { fetchArticles, fetchPages }
)(News);

