import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { fetchArticles } from '../redux/actions';

import Head from 'next/head'
import Header from '../components/Header'
import ArticleList from '../components/ArticleList'
import Hero2 from '../components/Hero2'

function News({ articles, fetchArticles }) {
    useEffect(() => {
        fetchArticles();
    }, []);

    return (
        <div>
            <Head>
                <title>Mediteran</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <div>
                <Header />
                <Hero2 />
                <ArticleList articles={articles} />
            </div>
        </div>
    )
}

const mapStateToProps = state => {
    return { articles: state.articles };
};

export default connect(
    mapStateToProps,
    { fetchArticles }
)(News);

