import React, { useEffect } from 'react';
import { useRouter } from 'next/router'
import { connect } from 'react-redux';
import { fetchArticles, fetchArticle } from '../../../redux/actions';

import Head from 'next/head'
import Header from '../../components/Header'
import Hero2 from '../../components/Hero2'
import ArticleData from '../../components/ArticleData'

function Article({ article, fetchArticle, articles, fetchArticles }) {
    const router = useRouter()
    const { id } = router.query

    useEffect(() => {
        fetchArticles();
        fetchArticle(id);
    }, []);

    return (
        <div>
            <Head>
                <title>Mediteran</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Header />
            <Hero2 />
            <ArticleData article={ article } articles={ articles } />
        </div>
    )
}

const mapStateToProps = state => {
    return {
        articles: state.articles,
        article: state.article
    };
};

export default connect(
    mapStateToProps,
    { fetchArticles, fetchArticle }
)(Article);
